apiVersion: v1
kind: Service
metadata:
  name: empapi
  labels:
    app: emp-app
    service: empapi
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: empapi