apiVersion: apps/v1
kind: Deployment
metadata:
  name: empapi
  labels:
    app: emp-app
spec:
  replicas: 1
  selector:
    matchLabels:
      service: empapi
  template:
    metadata:
      labels:
        app: emp-app
        service: empapi
    spec:
      containers:
        - name: empapi
          image: employee-api
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "128Mi" # 128 mb
              cpu: "200m" # 20% cpu
          ports:
            - containerPort: 80
              protocol: TCP

