apiVersion: v1
kind: Service
metadata:
  name: empui
  labels:
    app: emp-app
    service: empui
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: empui